import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import FooterTop from '../components/Footer';
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'GO Cart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        
            <Navbar />
            {children}
            <FooterTop />
          
      </body>
    </html>
    
  )
}
